### ISSUE TITLE
burndown fails for some repos with "$COMMIT does not have a branch assigned"

### ISSUE THREAD

**Issue by marsmensch** [src-d/hercules#120]
Tested with the newest v5 release on OS X 10.12.6 (16G1510).

Example failing run:

```
hercules --burndown --burndown-people --pb https://github.com/dashpay/dash | tee dash.pb | ./labours.py -m ownership
Reading the input... Enumerating objects: 94, done.
2018/10/23 14:27:27 parent 76d9eddfa471448ae3eda1e0430cf9fd77c8529b > 591e64dc3b657f7a974b6a7dfc736308be56bbad does not have a branch assigned
panic: parent 76d9eddfa471448ae3eda1e0430cf9fd77c8529b > 591e64dc3b657f7a974b6a7dfc736308be56bbad does not have a branch assigned

goroutine 1 [running]:
log.Panicf(0x4af5a55, 0x2e, 0xc000af3130, 0x2, 0x2)
	/Users/travis/.gimme/versions/go1.11.1.darwin.amd64/src/log/log.go:333 +0xda
gopkg.in/src-d/hercules.v5/internal/core.generatePlan.func3()
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/internal/core/forks.go:525 +0x4cc
gopkg.in/src-d/hercules.v5/internal/core.generatePlan(0xc0d53758e0, 0xc0d3ab9ad0, 0xc0d4f64de0, 0xc0d3ab9b00, 0xc0d4f64e10, 0xc00b37cf98, 0xb37cf98d3b52a80, 0x5bcf13ae)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/internal/core/forks.go:557 +0x1aa
gopkg.in/src-d/hercules.v5/internal/core.prepareRunPlan(0xc0d26c0000, 0x3a2e, 0x3c00, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/internal/core/forks.go:145 +0x111
gopkg.in/src-d/hercules.v5/internal/core.(*Pipeline).Run(0xc000af3c30, 0xc0d26c0000, 0x3a2e, 0x3c00, 0xc000aa4428, 0xc0d3a00ad0, 0x0)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/internal/core/pipeline.go:616 +0x9b
main.glob..func3(0x5607ca0, 0xc000a5a580, 0x1, 0x4)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/cmd/hercules/root.go:223 +0x723
github.com/spf13/cobra.(*Command).execute(0x5607ca0, 0xc000030060, 0x4, 0x4, 0x5607ca0, 0xc000030060)
	/Users/travis/gopath/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x5607ca0, 0x4aeb556, 0x26, 0xc00046683c)
	/Users/travis/gopath/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x5607ca0, 0x4007430, 0xc0000400b8)
	/Users/travis/gopath/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/cmd/hercules/root.go:429 +0x31
done
Traceback (most recent call last):
  File "./labours.py", line 1287, in <module>
    sys.exit(main())
  File "./labours.py", line 1140, in main
    header = reader.get_header()
  File "./labours.py", line 141, in get_header
    header = self.data["hercules"]
TypeError: 'NoneType' object is not subscriptable
```
Thanks a lot for your work!

**Comment by vmarkovtsev** [comment]
Thanks for reporting! The workaround is `--first-parent` while I am fixing the bug.

**Comment by marsmensch** [comment]
Thank you! Really excited about your work, awesome and great potential!

**Comment by vmarkovtsev** [comment]
@marsmensch Fixed.
![dash](https://user-images.githubusercontent.com/2793551/47518212-97488980-d88a-11e8-87d9-5b1515b40905.png)
