### ISSUE TITLE
Burndown files empty history panic

### ISSUE THREAD

**Issue by smacker** [src-d/hercules#138]
```
smacker in ~/Downloads
$ ./hercules --burndown --burndown-files https://github.com/sirupsen/logrus
finalizing...panic: empty history

goroutine 1 [running]:
gopkg.in/src-d/hercules.v5/leaves.(*BurndownAnalysis).groupSparseHistory(0xc002b943c0, 0xc002d2aff0, 0x754, 0x8, 0xc0000d9990, 0x3f, 0x754)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/leaves/burndown.go:1221 +0x726
gopkg.in/src-d/hercules.v5/leaves.(*BurndownAnalysis).Finalize(0xc002b943c0, 0x4cb5f80, 0xc000122180)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/leaves/burndown.go:371 +0x14a
gopkg.in/src-d/hercules.v5/internal/core.(*Pipeline).Run(0xc001f1bc30, 0xc002262000, 0x3c1, 0x400, 0xc002550708, 0xc000ba0300, 0x0)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/internal/core/pipeline.go:686 +0x5fa
main.glob..func3(0x56a64a0, 0xc000a32960, 0x1, 0x3)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/cmd/hercules/root.go:240 +0x76b
gopkg.in/src-d/hercules.v5/vendor/github.com/spf13/cobra.(*Command).execute(0x56a64a0, 0xc0000ba0d0, 0x3, 0x3, 0x56a64a0, 0xc0000ba0d0)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
gopkg.in/src-d/hercules.v5/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x56a64a0, 0x0, 0x4b31e30, 0x4c)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
gopkg.in/src-d/hercules.v5/vendor/github.com/spf13/cobra.(*Command).Execute(0x56a64a0, 0x40075a0, 0xc000096058)
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/travis/gopath/src/gopkg.in/src-d/hercules.v5/cmd/hercules/root.go:471 +0x31
```

the same error happens on master

**Comment by vmarkovtsev** [comment]
Thanks for reporting. This error appears only with `--burndown-files`. The fix is simple, stay tuned.
