### ISSUE TITLE
[bug] devs visualization fails

### ISSUE THREAD

**Issue by EgorBu** [src-d/hercules#190]
Hi,
when I tried to launch this command
`python3 labours.py -m devs -i res.pb -o image.png`
I got 
```console
Reading the input... done
Picking top 100 developers by commit count
Calculating the distance matrix
Ordering the series
Plotting
Traceback (most recent call last):
  File "/home/ec2-user/scripts/hercules/labours.py", line 1618, in <module>
    sys.exit(main())
  File "/home/ec2-user/scripts/hercules/labours.py", line 1593, in main
    modes[args.mode]()
  File "/home/ec2-user/scripts/hercules/labours.py", line 1560, in devs
    show_devs(args, reader.get_name(), *reader.get_header(), data)
  File "/home/ec2-user/scripts/hercules/labours.py", line 1353, in show_devs
    axes[-1].xaxis.set_major_locator(matplotlib.dates.YearLocator(interval=interval))
TypeError: __init__() got an unexpected keyword argument 'interval'
```

it happens because `YearLocator` doesn't have this argument ([link](https://matplotlib.org/api/dates_api.html#matplotlib.dates.YearLocator)).
As I understand the logic - it should be
`matplotlib.dates.YearLocator(base=max(1, interval // 12))`

**Comment by vmarkovtsev** [comment]
@EgorBu Feel free to PR the fix :+1:
