### ISSUE TITLE
panic: context deadline exceeded

### ISSUE THREAD

**Issue by nono** [src-d/hercules#193]
Hello,

I've tried hercules on the github.com/cozy/cozy-stack repository, and it has failed with this error:

```
$ docker run --rm srcd/hercules hercules --burndown --burndown-files --burndown-people --couples --shotness --devs --pb https://github.com/cozy/cozy-stack >hercules.out

panic: context deadline exceeded

goroutine 1 [running]:
gopkg.in/src-d/hercules.v7/internal/plumbing/uast.(*Extractor).Initialize(0xc423758c80, 0xc420a79740, 0x0, 0x0)
	/root/src/gopkg.in/src-d/hercules.v7/internal/plumbing/uast/uast.go:175 +0x2b9
gopkg.in/src-d/hercules.v7/internal/core.(*Pipeline).Initialize(0xc471317c10, 0xc420a79410, 0xc473a60840, 0x7f37cea07bb8)
	/root/src/gopkg.in/src-d/hercules.v7/internal/core/pipeline.go:664 +0x47d
main.glob..func3(0x1e6a060, 0xc42046ef80, 0x1, 0x8)
	/root/src/gopkg.in/src-d/hercules.v7/cmd/hercules/root.go:265 +0x78a
gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra.(*Command).execute(0x1e6a060, 0xc4200300a0, 0x8, 0x8, 0x1e6a060, 0xc4200300a0)
	/root/src/gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1e6a060, 0xc4202814b0, 0xc420281480, 0xc4200dab00)
	/root/src/gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra/command.go:852 +0x30a
gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra.(*Command).Execute(0x1e6a060, 0xc4200a6058, 0x0)
	/root/src/gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/root/src/gopkg.in/src-d/hercules.v7/cmd/hercules/root.go:509 +0x31
```

**Comment by vmarkovtsev** [comment]
Hi @nono

This error signals that the Babelfish server (parser engine) is not running. You should launch it following the [docs](https://docs.sourced.tech/babelfish/using-babelfish/getting-started#running-with-docker-recommended).

**Comment by ntziolis** [comment]
Seeing the same issue. Shouldn't the Babelfish server be already running when using the docker image?
