### ISSUE TITLE
Panic running analysis

### ISSUE THREAD

**Issue by erizocosmico** [src-d/hercules#216]
panic: time may not be >= MaxUint32

```
goroutine 1 [running]:
gopkg.in/src-d/hercules.v7/internal/burndown.(*File).Update(0xc00049cb40, 0xffffffff, 0x1e, 0x0, 0x1)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/internal/burndown/file.go:155 +0xfec
gopkg.in/src-d/hercules.v7/leaves.(*BurndownAnalysis).handleModification.func1(0xc00fc125ff, 0xc00fc12580, 0x1)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/leaves/burndown.go:1240 +0x14c
gopkg.in/src-d/hercules.v7/leaves.(*BurndownAnalysis).handleModification(0xc001304690, 0xc00fb22300, 0x3ffff, 0xc00fc20750, 0xc00fc20a50, 0x85085e, 0xc00fa97b60)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/leaves/burndown.go:1265 +0x91c
gopkg.in/src-d/hercules.v7/leaves.(*BurndownAnalysis).Consume(0xc001304690, 0xc00fa97b60, 0x2120d60, 0x9, 0xc006bed2c8)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/leaves/burndown.go:361 +0x380
gopkg.in/src-d/hercules.v7/internal/core.(*Pipeline).Run(0xc0085d3c20, 0xc00139e000, 0x145, 0x200, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/internal/core/pipeline.go:763 +0xfa9
main.glob..func3(0x20c4da0, 0xc00013f300, 0x1, 0x8)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/cmd/hercules/root.go:269 +0x840
gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra.(*Command).execute(0x20c4da0, 0xc0000dc010, 0x8, 0x8, 0x20c4da0, 0xc0000dc010)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x20c4da0, 0xc00027b6a0, 0xc00027b670, 0xc0000feb00)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra.(*Command).Execute(0x20c4da0, 0x843150, 0xc0000b4058)
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/travis/gopath/src/gopkg.in/src-d/hercules.v7/cmd/hercules/root.go:509 +0x31
```

**Comment by vmarkovtsev** [comment]
How to reproduce:

```
hercules --burndown --burndown-people --people-dict /tmp/ident https://github.com/src-d/go-git.v4
```

where `/tmp/ident` is only one line.
