### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 1: invalid start byte

### ISSUE THREAD

**Issue by lerra** [src-d/hercules#324]
Hi, I am running the following that is failing,

```
hercules combine $A | labours -m burndown-person -o burndown-person.png
Reading the input... Traceback (most recent call last):
  File "/usr/local/bin/labours", line 11, in <module>
    load_entry_point('labours==10.5.2', 'console_scripts', 'labours')()
  File "/usr/local/lib/python3.6/dist-packages/labours/cli.py", line 154, in main
    reader = read_input(args)
  File "/usr/local/lib/python3.6/dist-packages/labours/readers.py", line 390, in read_input
    reader.read(args.input)
  File "/usr/local/lib/python3.6/dist-packages/labours/readers.py", line 78, in read
    data = yaml.load(sys.stdin, Loader=loader)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 702, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 903, in _yaml.CParser._parse_next_event
  File "ext/_yaml.pyx", line 912, in _yaml.input_handler
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 1: invalid start byte
```

$A is a variable of 733 pd files generated with the following command

```
for D in *; do
    if [ -d "${D}" ]; then
	hercules --burndown --burndown-people --pb /io/${D} > hercules/burndown-person/${D}.pb
    fi
done
```
This is the relaventt output of "hercules combine $A"
```
��
(5263b0a6fa8bd2a0af2246106d7b1b076aac75aa��/io/repo1 & /io/repo2 & .....and so on to /io/repo733  ����(����0��8���B
```

This is the error I get
``

Any idea on what's going wrong? I tried to pipe the output and decode utf8 but I just got another error

**Comment by vmarkovtsev** [comment]
I think it failed to detect the input format and thus needs to set it explicitly:

```
hercules combine $A | labours -f pb -m burndown-person -o burndown-person.png
```

**Comment by lerra** [comment]
You are right, my bad!
