### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1: invalid start byte

### ISSUE THREAD

**Issue by pmajkutewicz** [src-d/hercules#333]
After executing 
`./hercules --burndown --burndown-people --pb ~/path/git_project | labours -m ownership`

I'm getting:
```
Reading the input... Warning: failed to import yaml.CLoader, falling back to slow yaml.Loader
Traceback (most recent call last):
  File "/hercules//venv/bin/labours", line 11, in <module>
    sys.exit(main())
  File "/hercules//venv/lib/python3.6/site-packages/labours/cli.py", line 154, in main
    reader = read_input(args)
  File "/hercules//venv/lib/python3.6/site-packages/labours/readers.py", line 390, in read_input
    reader.read(args.input)
  File "/hercules//venv/lib/python3.6/site-packages/labours/readers.py", line 78, in read
    data = yaml.load(sys.stdin, Loader=loader)
  File "/hercules//venv/lib/python3.6/site-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/hercules//venv/lib/python3.6/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/hercules//venv/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/hercules//venv/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/hercules//venv/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1: invalid start byte
```

Any advices?

**Comment by vmarkovtsev** [comment]
I think `labours -f pb`should work. I need to properly fix this, that's not the first issue about it.
