### ISSUE TITLE
labours hangs

### ISSUE THREAD

**Issue by pythonmobile** [src-d/hercules#361]
labours -m ownership
Reading the input...  <hangs>

Ctrl + C
```
Reading the input... ^CTraceback (most recent call last):
  File "/home/joe/.pyenv/versions/3.8.2/bin/labours", line 8, in <module>
    sys.exit(main())
  File "/home/joe/.pyenv/versions/3.8.2/lib/python3.8/site-packages/labours/cli.py", line 154, in main
    reader = read_input(args)
  File "/home/joe/.pyenv/versions/3.8.2/lib/python3.8/site-packages/labours/readers.py", line 429, in read_input
    buffer = stream.read(1 << 16)
KeyboardInterrupt
```
I've the latest version of labours. Hercules:

Version: 10
Git:     4ac296216434bd4a7869f0aaf814b47cf26b2c58

**Comment by 0xjac** [comment]
I am having a similar issue. `scipy<1.2.2,>=0.19.0` is too old for my distro. Even if I downgrade scipy in a virtualenv, scipy 1.2.1 will not work with python 3.8. Any chance of an update to scipy 1.5?
