### ISSUE TITLE
UTF-8 characters in log

### ISSUE THREAD

**Issue by kown7** [src-d/hercules#377]
When a name has an umlaut it will fail with

```bash
Traceback (most recent call last):
  File "/usr/local/bin/labours", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/labours/cli.py", line 449, in main
    modes[mode]()
  File "/usr/local/lib/python3.6/dist-packages/labours/cli.py", line 304, in couples_people
    *train_embeddings(*reader.get_people_coocc(), tmpdir=args.tmpdir),
  File "/usr/local/lib/python3.6/dist-packages/labours/embeddings.py", line 52, in train_embeddings
    out.write(vocabulary)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 145: ordinal not in range(128)
```

**Comment by vmarkovtsev** [comment]
Hi @kown7 PTAL at the docs: https://github.com/src-d/hercules#bad-unicode-errors
Feel free to ping if it does not help.

**Comment by kown7** [comment]
Thanks for the pointer, missed that completely. RTFM and so.

Now I'm stuck at 

```bash
Running: couples-shotness
Traceback (most recent call last):
  File "/usr/local/bin/labours", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/labours/cli.py", line 449, in main
    modes[mode]()
  File "/usr/local/lib/python3.6/dist-packages/labours/cli.py", line 315, in couples_shotness
    *train_embeddings(*reader.get_shotness_coocc(), tmpdir=args.tmpdir),
  File "/usr/local/lib/python3.6/dist-packages/labours/readers.py", line 145, in get_shotness_coocc
    index = ["%s:%s" % (i["file"], i["name"]) for i in shotness]
TypeError: 'NoneType' object is not iterable
```

This is certainly unrelated.
