### ISSUE TITLE
"internal diff error" and panic

### ISSUE THREAD

**Issue by vearutop** [src-d/hercules#4]
With version 
```
commit 4d54d684c2f14f387fbf38b7badfb69641785e05
Author: Vadim Markovtsev <vadim@sourced.tech>
Date:   Fri Apr 21 15:16:12 2017 +0200
```

```
hercules https://github.com/php-yaoi/php-yaoi
```

```
modules/Sql/Sql_Expression.php: internal diff error/github.com/php-yaoi/php-yaoi
.......
81f4da7d6fa017c175c846964c4d15f40c4700d3: modification error
panic: rbtree internal assertion failed [recovered]
	panic: rbtree internal assertion failed [recovered]
	panic: rbtree internal assertion failed

goroutine 1 [running]:
gopkg.in/src-d/hercules%2ev1.(*Analyser).Analyse.func3.1(0xc421927c20)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/analyser.go:330 +0x142
panic(0x135f5c0, 0xc42033abb0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:489 +0x2cf
gopkg.in/src-d/hercules%2ev1.(*Analyser).handleModification.func2.1(0xc420de2100, 0xc420bb3000, 0xeb2, 0xc42160f500, 0x13fe)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/analyser.go:152 +0x454
panic(0x135f5c0, 0xc42033abb0)
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:489 +0x2cf
gopkg.in/src-d/hercules%2ev1.doAssert(0xc420f31200)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/rbtree.go:256 +0x77
gopkg.in/src-d/hercules%2ev1.Iterator.Next(0x0, 0x0, 0x179, 0xc420f31200)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/rbtree.go:232 +0x30
gopkg.in/src-d/hercules%2ev1.(*File).Update(0xc4202145f0, 0x179, 0x65, 0x28, 0x2)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/file.go:131 +0x55d
gopkg.in/src-d/hercules%2ev1.(*Analyser).handleModification.func2(0xc420de2100, 0xc420bb3000, 0xeb2, 0xc42160f500, 0x13fe, 0xc421927a50, 0xc421927a38, 0xc421927a68, 0xc421927968, 0x28, ...)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/analyser.go:167 +0x26c
gopkg.in/src-d/hercules%2ev1.(*Analyser).handleModification(0xc421927ea0, 0xc420de2100, 0x179, 0xc42051b9e0, 0xc42051ba10)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/analyser.go:181 +0x4c2
gopkg.in/src-d/hercules%2ev1.(*Analyser).Analyse.func3(0xc421927c20, 0xc421927ea0, 0xc421927c28, 0x179, 0xc42051b9e0, 0xc42051ba10)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/analyser.go:333 +0x80
gopkg.in/src-d/hercules%2ev1.(*Analyser).Analyse(0xc421927ea0, 0xc42114a000, 0x1cf, 0x200, 0x1, 0xb, 0x0)
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/analyser.go:334 +0x620
main.main()
	/Users/vpoturaev/golang/src/gopkg.in/src-d/hercules.v1/cmd/hercules/main.go:123 +0x912
```

**Comment by vmarkovtsev** [comment]
Thank you! Will have a look.

**Comment by saintnik2015** [comment]
Same issue

**Comment by vmarkovtsev** [comment]
@vearutop @saintnik2015 Guys I seem to fix this, please test

**Comment by saintnik2015** [comment]
After reinstalling hercules ab initio it works well.
