### ISSUE TITLE
Hercules fails on facebook/react

### ISSUE THREAD

**Issue by smacker** [src-d/hercules#49]
```
$ hercules --quiet --burndown --burndown-people https://github.com/facebook/react | python3 labours.py -m ownership
Warning: clint is not installed, no fancy progressbars in the terminal for you.
Reading the input... src/renderers/shared/fiber/__tests__/ReactIncrementalSideEffects-test.js: internal diff error
Update(1385, 742, 2 (0), 1 (0))
====TREE AFTER====
0 1803368
15 3736889
16 1803368
17 1295532
19 787735
20 1803612
21 1803368
22 3736889
24 1803368
26 4556073
30 1803368
31 8177001
33 1803368
35 1803404
36 8177001
37 1803368
39 1295532
40 1803368
55 8177001
56 1803368
59 8177001
60 1803368
62 1803477
71 8177001
76 1803477
83 8177001
84 1803477
87 2999524
88 1803477
93 2999524
94 1803477
98 1803477
107 8177001
110 1803477
116 8177001
117 1803477
120 8177001
121 1803477
123 1803477
131 8177001
134 1803477
140 2999524
141 1803477
146 8177001
147 1803477
149 1803485
168 8177001
173 1803485
180 8177001
181 1803485
186 8177001
187 1803485
192 8177001
193 1803485
196 8177001
197 1803485
218 8177001
221 1803485
228 8177001
229 1803485
234 8177001
235 1803485
240 8177001
241 1803485
243 1295532
244 1803368
245 1803404
246 1803368
262 2999524
263 1803404
264 1803368
267 3736755
268 2999524
269 1803404
273 1295532
274 1803404
291 8177001
292 1803368
293 1803404
294 3736755
295 1803404
296 8177001
297 1803404
300 8177001
301 1803404
303 1295532
304 1803404
318 8177001
320 1803404
323 8177001
324 1803404
332 2999524
333 1803404
339 3736755
340 1803404
342 2999524
343 1803404
346 7898444
347 1803404
350 1803443
351 1803404
356 2999524
357 1803404
361 1295532
362 1803404
397 2999524
398 1803404
404 3736755
405 1803404
407 2999524
408 1803404
411 7898444
412 1803404
421 2999524
422 1803404
426 3736841
428 787803
429 3736841
458 1295532
459 1803404
469 8177001
470 1803368
472 1803443
475 1803477
476 1803443
493 3736755
494 2999524
495 1803443
497 8177001
498 1803443
501 3736755
502 2999524
503 8177001
504 1803443
505 3736755
506 2999524
507 1803443
512 8177001
514 1803443
516 2999524
517 1803443
518 3736755
519 2999524
520 1803443
525 8177001
527 1803443
529 1803477
531 2999524
532 1803443
533 1803477
534 1803443
537 8177001
539 1803443
542 2999524
543 1803443
549 1803477
584 3736841
585 2999524
586 1803477
588 8177001
589 1803477
597 2999524
598 8177001
599 1803477
601 3736877
602 1803477
605 2999524
606 1803477
615 8177001
617 1803477
627 2999524
628 1803477
637 8177001
639 1803477
651 2999524
652 1803477
661 8177001
663 1803477
672 2999524
673 1803477
682 8177001
684 1803477
687 1803481
688 1803477
689 1803443
690 1803479
698 8177001
699 1803479
702 8177001
703 1803479
724 2999524
725 8177001
726 1803479
733 3736841
734 2999524
735 1803479
756 3736841
757 2999524
758 1803479
776 2999524
777 1803479
788 3736877
789 1803479
790 1803368
794 1803443
809 2999524
810 1803443
814 2999524
815 1803443
823 3736805
852 1803443
853 1803477
999 1803477
1000 4556073
1001 1803477
1060 4556073
1062 7095615
1063 4556073
1068 1803477
1073 3736798
1097 1803368
1098 -1
====END====
Burndown failed on commit #4568 b1b4a2fb252f26fe10d29ba60d85ff89a85ff3ec
panic: DiffDelete may not appear after DiffInsert/DiffDelete

goroutine 1 [running]:
main.glob..func3(0x5280cc0, 0xc4201cb900, 0x1, 0x4)
	/Users/smacker/go/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:210 +0xc25
github.com/spf13/cobra.(*Command).execute(0x5280cc0, 0xc420010150, 0x4, 0x4, 0x5280cc0, 0xc420010150)
	/Users/smacker/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x5280cc0, 0x26, 0xc420462b71, 0x0)
	/Users/smacker/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0x5280cc0, 0x0, 0xc42019ff70)
	/Users/smacker/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/Users/smacker/go/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:398 +0x31
done
```

**Comment by smacker** [comment]
similar error on `vuejs/vue`

**Comment by vmarkovtsev** [comment]
`--no-diff-cleanup` fixes this error. Looks like the "automatic awesomizer" is not very awesome.

**Comment by vmarkovtsev** [comment]
This is fixed, no extra option is required and `v3` tag is updated. Thanks for reporting!
