### ISSUE TITLE
IndexError in labours.py

### ISSUE THREAD

**Issue by AlekSi** [src-d/hercules#5]
```
$ hercules https://github.com/go-reform/reform | python3 labours.py --resample month
Traceback (most recent call last):
  File "labours.py", line 168, in <module>
    sys.exit(main())
  File "labours.py", line 79, in main
    matrix[i, i] += matrix[i, :i].sum()
IndexError: index 12 is out of bounds for axis 1 with size 12
```
```
$ hercules https://github.com/go-reform/reform | python3 labours.py
Traceback (most recent call last):
  File "labours.py", line 168, in <module>
    sys.exit(main())
  File "labours.py", line 136, in main
    if pyplot.xlim()[1] - locs[-1] >= (locs[-1] - locs[-2]) / 2:
IndexError: list index out of range
```

**Comment by vmarkovtsev** [comment]
Thanks! I believe I fixed this.

**Comment by vmarkovtsev** [comment]
![reform](https://cloud.githubusercontent.com/assets/2793551/26755306/fd8b7cb6-488a-11e7-8d5a-649c44cd27a6.png)

**Comment by vmarkovtsev** [comment]
There is still an anomaly with the ending.

**Comment by vmarkovtsev** [comment]
![reform](https://cloud.githubusercontent.com/assets/2793551/26786177/f9e6526c-4a05-11e7-8cf4-3b676b6c0729.png)
