### ISSUE TITLE
Hercules fails on emberjs/ember.js

### ISSUE THREAD

**Issue by smacker** [src-d/hercules#50]
```
$ hercules --quiet --burndown --burndown-people https://github.com/emberjs/ember.js | python3 labours.py -m ownership
Warning: clint is not installed, no fancy progressbars in the terminal for you.
Reading the input... file to vendor/ruby/1.9.1/bundler/gems/abbot-from-scratch-754164ff560e 754164ff560e2597b62fb326358fb8b9f7fc3ed4
BlobCache failed on commit #255 22df75f1c6b95ec4c4b2e68b16d308a443cf6bf6
panic: file not found

goroutine 1 [running]:
main.glob..func3(0x5280cc0, 0xc420a30100, 0x1, 0x4)
	/Users/smacker/go/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:210 +0xc25
github.com/spf13/cobra.(*Command).execute(0x5280cc0, 0xc420010150, 0x4, 0x4, 0x5280cc0, 0xc420010150)
	/Users/smacker/go/src/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x5280cc0, 0x26, 0xc420a36071, 0x0)
	/Users/smacker/go/src/github.com/spf13/cobra/command.go:831 +0x30e
github.com/spf13/cobra.(*Command).Execute(0x5280cc0, 0x0, 0xc42019ff70)
	/Users/smacker/go/src/github.com/spf13/cobra/command.go:784 +0x2b
main.main()
	/Users/smacker/go/src/gopkg.in/src-d/hercules.v3/cmd/hercules/root.go:398 +0x31
done
```

**Comment by vmarkovtsev** [comment]
This is known: ember repo sucks. https://github.com/src-d/hercules/issues/12
