### ISSUE TITLE
docker run failed issue

### ISSUE THREAD

**Issue by murphygithub** [src-d/hercules#78]
docker run --rm srcd/hercules hercules --burndown --pb https://github.com/git/git | docker run --rm -i -v $(pwd):/io srcd/hercules labours.py -f pb -m project -o /io/git_git.png

 get below msg

>>> You need to generate internal/pb/pb_pb2.py - run "make"

Traceback (most recent call last):
  File "/usr/local/bin/labours.py", line 1258, in <module>
    sys.exit(main())
  File "/usr/local/bin/labours.py", line 1121, in main
    reader = read_input(args)
  File "/usr/local/bin/labours.py", line 344, in read_input
    reader.read(args.input)
  File "/usr/local/bin/labours.py", line 234, in read
    raise e from None
  File "/usr/local/bin/labours.py", line 230, in read
    from internal.pb.pb_pb2 import AnalysisResults
ModuleNotFoundError: No module named 'internal'

**Comment by vmarkovtsev** [comment]
Hi! Do you mean that this error happens when you execute `docker run`? If so, why "docker install failed issue"?

**Comment by vmarkovtsev** [comment]
Should be fixed now. Thanks for reporting.

**Comment by murphygithub** [comment]
Just try and got same error

docker run --rm srcd/hercules hercules --burndown --pb https://github.com/git/git | docker run --rm -i -v $(pwd):/io srcd/hercules labours.py -f pb -m project -o /io/git_git.png

Reading the input... 

>>> You need to generate internal/pb/pb_pb2.py - run "make"

Traceback (most recent call last):
  File "/usr/local/bin/labours.py", line 1258, in <module>
    sys.exit(main())
  File "/usr/local/bin/labours.py", line 1121, in main
    reader = read_input(args)
  File "/usr/local/bin/labours.py", line 344, in read_input
    reader.read(args.input)
  File "/usr/local/bin/labours.py", line 234, in read
    raise e from None
  File "/usr/local/bin/labours.py", line 230, in read
    from internal.pb.pb_pb2 import AnalysisResults
ModuleNotFoundError: No module named 'internal'
